
keywords = {
    'begin' : 'TK_BEGIN',
    'array' : 'TK_ARRAY',
    'const' : 'TK_CONST',
    'class' : 'TK_CLASS',
    'else'  : 'TK_ELSE',
    'do' : 'TK_DO',
    'if' : 'TK_IF',
    'integer' : 'TK_INT',
    'for' : 'TK_FOR',
    'var' : 'TK_VAR',
    'procedure' : 'TK_PROCEDURE',
    'program' : 'TK_PROGRAM',
    'end' : 'TK_END',
    'then' : 'TK_THEN',
    'downto' : 'TK_DOWNTO',
    'string' : 'TK_STRING',
    'real' : 'TK_REAL',
    'boolean' : 'TK_BOOLEAN',
}


operators = {
    '+' : 'TK_PLUS',
    '-' : 'TK_MINUS',
    '*' : 'TK_MUL',
    '/' : 'TK_DIV',
    '>' : 'TK_GREATER',
    '<' : 'TK_LESS',
    ':=' : 'TK_ASSIGN',
    '=' : 'TK_EQUAL',
    '<=' : 'TK_LESS_EQ',
    '>=' : 'TK_GREATER_EQ',
    '<>' : 'TK_NOT_EQ',
    'in' : 'TK_IN',
    '&' : 'TK_BIT_AND', 
    'and' : 'TK_AND',
    'shl' : 'TK_LEFT_SHIFT',
    'shr' : 'TK_RIGHT_SHIFT',
}

symbols = {
    '.' : 'TK_PERIOD',
    ',' : 'TK_COMMA',
    '!' : 'TK_EXCLA',
    '?' : 'TK_QUESTION',
    '$' : 'TK_HASH',
    '#' : 'TK_POUND',
    '&' : 'TK_AMP',
    ':' : 'TK_COLON',
    ';' : 'TK_SCOLON',
    '(' : 'TK_LEFT_PAREN',
    ')' : 'TK_RIGHT_PAREN',
}
