
keywords = {
    'begin' : 'TK_BEGIN',
    'array' : 'TK_ARRAY',
    'const' : 'TK_CONST',
    'class' : 'TK_CLASS',
    'else'  : 'TK_ELSE',
    'do' : 'TK_DO',
    'if' : 'TK_IF',
    'integer' : 'TK_INT',
    'for' : 'TK_FOR',
    'var' : 'TK_VAR',
    'procedure' : 'TK_PROCEDURE',
    'program' : 'TK_PROGRAM',
    'end' : 'TK_END',
    'then' : 'TK_THEN',
    'downto' : 'TK_DOWNTO',
    'string' : 'TK_STRING',
    'real' : 'TK_REAL',
    'mod':'TK_MOD_OP'
    'boolean' : 'TK_BOOLEAN',
    'write' : 'TK_WRITE', 
    'writeln' : 'TK_WRITELN',
    'mod':'TK_MOD',
    'not':'TK_NOT',
    'and':'TK_AND',
    'array':'TK_ARRAY',
    'of':'TK_OF',
    'case':'TK_CASE',
    'label':'TK_LABEL',
    'nil':'TK_NIL',
    'until':'TK_UNTIL',
    'or':'TK_OR',
    'switch':'TK_SWITCH',
    'to':'TK_TO',
    'type':'TK_TYPE',
    'while':'TK_WHILE',
    'with':'TK_WITH',
  
}


operators = {
    '+' : 'TK_PLUS',
    '-' : 'TK_MINUS',
    '*' : 'TK_MUL',
    '/' : 'TK_DIV',
    '>' : 'TK_GREATER',
    '<' : 'TK_LESS',
    ':=' : 'TK_ASSIGN',
    '=' : 'TK_EQUAL',
    '<=' : 'TK_LESS_EQ',
    '>=' : 'TK_GREATER_EQ',
    '<>' : 'TK_NOT_EQ',
    'in' : 'TK_IN',
    '&' : 'TK_BIT_AND', 
    'shl' : 'TK_LEFT_SHIFT',
    'shr' : 'TK_RIGHT_SHIFT',
}

symbols = {
    '.' : 'TK_PERIOD',
    ',' : 'TK_COMMA',
    '!' : 'TK_EXCLA',
    '?' : 'TK_QUESTION',
    '$' : 'TK_HASH',
    '#' : 'TK_POUND',
    '&' : 'TK_AMP',
    ':' : 'TK_COLON',
    ';' : 'TK_SCOLON',
    '(' : 'TK_LEFT_PAREN',
    ')' : 'TK_RIGHT_PAREN',
    '"' : 'TK_QUOTE', 
    ':=': 'TK_ASGMT',
}

opcodes = {
    'push' : 0,
    'move' : 1,
    'movei': 2,
    'mult' : 3,
    'pop'  : 4,
    'halt' : 5,
    'print': 6,
    'println': 7,
    'add' : 8,
    'sub' : 9,
    'dup' : 10,
    'exch' : 11,
    'div' : 12,
}
